services:
  - type: web
    name: skillsync-backend
    runtime: docker
    rootDir: backend
    plan: free
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_SQL_INIT_MODE
        value: never
      - key: APP_FRONTEND_URL
        value: https://skillsync-frontend.onrender.com
      - key: APP_OAUTH2_REDIRECT_URI
        value: https://skillsync-frontend.onrender.com/oauth2/callback
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRATION
        value: "86400000"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: ADZUNA_APP_ID
        sync: false
      - key: ADZUNA_APP_KEY
        sync: false
      - key: SPRING_MAIL_USERNAME
        sync: false
      - key: SPRING_MAIL_PASSWORD
        sync: false

  - type: static
    name: skillsync-frontend
    rootDir: frontend/frontend
    buildCommand: npm ci && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://skillsync-backend.onrender.com/api
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
